# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39e5a89b3f7aa7e443eb373c7ad294db6b8dd3cf3838ee69009141aa0fdeb652daa2b918c0c643963298cd6c9175fc38b6f76f02c3e13b3cc41085b3447e8df8

test:
  secret_key_base: f431ea58a44cf270b362901f62b6919952d229de3e2342e47b5255d3c1be0e332f69201c41c2fe827eb3c8be31228a1ca92e0e8326b7632c9d9383085e6fc00b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
